/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Email = IDL.Text;
export const Timestamp = IDL.Int;
export const WaitlistEntry = IDL.Record({
  'email' : Email,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'addToWaitlist' : IDL.Func([Email], [], []),
  'getAllWaitlistEntriesSorted' : IDL.Func(
      [],
      [IDL.Vec(WaitlistEntry)],
      ['query'],
    ),
  'getTotalWaitlistEntries' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Email = IDL.Text;
  const Timestamp = IDL.Int;
  const WaitlistEntry = IDL.Record({
    'email' : Email,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'addToWaitlist' : IDL.Func([Email], [], []),
    'getAllWaitlistEntriesSorted' : IDL.Func(
        [],
        [IDL.Vec(WaitlistEntry)],
        ['query'],
      ),
    'getTotalWaitlistEntries' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };